### PR TITLE
Changes to gas fee estimations; Corrected "rawTransaction"

### PR DESCRIPTION
**Pull request by Zzzero-hash**
Hi,

I admire your work on this project and I wanted to contribute to it. I made some minor changes to the order.py script, and have been testing it for a while. I believe I fixed the estimate gas fee problem you were having an issue with with in your TODO note. Take a look and let me know what you think. I also made a minor syntax change to Line 112 in your original code of order.py, rawTransaction gets called correctly by raw_transaction. Again, cheers and thanks for so much hard work on this.

### CODE REVIEW

**Comment by snipermonke01** [comment]
Thanks for the work on this, really appreciated!

I think it usage of raw_transaction and rawTransaction will vary depending on the version of py web3 installed. You can see in the checksum address conversion function i have a try/except block that supports this.

https://github.com/snipermonke01/gmx_python_sdk/blob/main/gmx_python_sdk/scripts/v2/gmx_utils.py#L201-L204

it might be more pertinent to check the version of the web3 package and call the version of attribute appropriate to the version

eg:

```
import web3

if web3.__version__ == x:
    ...
```
Let me know your thoughts

**Comment by Zzzero-hash** [comment]
Of course, this library is amazing, and I would love to contribute. You are correct, the syntax for web3==6.10 would throw an error for rawTransaction and should be raw_transaction. I see your example in the gmx_utils.py.  With a little elbow grease it could be updated to work with the latest versions of web3 and older ones. Support from 6.10 up to the current 7.xx release? Let me know your thoughts and I'll work something up.

**Comment by snipermonke01** [comment]
Do you mind editing to merge from staging please?

The structure should follow new_branch -> staging -> main

This way we can bundle updates into new releases of the pip package.

Thanks!

**Comment by Zzzero-hash** [comment]
Hi absolutely, I apologize. I wasn't sure where to open the PR. Thank you.

**Comment by snipermonke01** [comment]
I included the changes you made into another branch i was working on anyway so the PR is now longer required.

Thanks again for your help on this!

**Comment by Zzzero-hash** [comment]
Glad to help out! Great work on the updated code.

**Pull request closed without merging**
